image: Ubuntu1804 # образ для сборки
stack: node 12 # окружение
version: 1.9.1
branches:
  only:
    - master
cache: 
  - node_modules
install:
  - npm install # команда установки зависимостей
build: off
test_script:
- npm run lint && npm test # скрипт сборки